IBM/ibm-event-automation

- README.md
- support/README.md
- support/ibm-events-must-gather
- support/template-yaml/must-gather-job.yaml
- support/template-yaml/namespace.yaml
- support/template-yaml/role-binding.yaml
- support/template-yaml/role.yaml
- support/template-yaml/service-account.yaml
Initial upload to cover ES, EEM and EP
> Initialise support folder with tooling

- support/ibm-events-must-gather
- Minor alterations to use the older image name whilst we await the repackage
> Utilise older image name temporarily

- flink/README.md
- flink/cr-examples/flinkdeployment/README.md
- flink/cr-examples/flinkdeployment/minimal-production.yaml
- flink/cr-examples/flinkdeployment/production-application-cluster.yaml
- flink/cr-examples/flinkdeployment/production.yaml
- flink/cr-examples/flinkdeployment/quick-start.yaml
> Add Flink samples.

- flink/cr-examples/flinkdeployment/README.md
- flink/cr-examples/flinkdeployment/minimal-production.yaml
- flink/cr-examples/flinkdeployment/production-application-cluster.yaml
Add changes for Flink samples for 1.0.1.
> Add changes for Flink 1.0.1

- event-streams/README.md
- event-streams/cr-examples/README.md
- event-streams/cr-examples/eventstreams-georeplicator/README.md
- event-streams/cr-examples/eventstreams/README.md
- event-streams/cr-examples/eventstreams/kubernetes/README.md
- event-streams/cr-examples/eventstreams/openshift/README.md
- event-streams/cr-examples/kafka-connect/README.md
- event-streams/cr-examples/kafka-mirror-maker-2/README.md
- event-streams/cr-examples/kafka-user/README.md
- event-streams/grafana-dashboards/README.md
- event-streams/kibana-dashboards/README.md
- event-streams/metrics-config/README.md
- event-streams/metrics-config/metrics-config.yaml
Samples update for Event Streams Release 11.2.2/3.2.2
> feat: Add es samples for 11.2.2

- event-streams/cr-examples/README.md
- event-streams/cr-examples/kafka-mirror-maker-2/README.md
Review Comments : https://github.com/IBM/ibm-event-automation/pull/15#discussion_r1276524265
> fix: Update Readme for the folders

- event-streams/jmxtrans/README.md
Signed-off-by: Vignesh Kumar Elumalai <vigneshkumar.elumalai@ibm.com>
> replace JMXTrans to jmxtrans

- flink/cr-examples/flinkdeployment/production-application-cluster.yaml
- flink/cr-examples/flinkdeployment/production.yaml
Suppress useless properties in Flink samples.
> Add changes for Flink 1.0.2

- support/event-automation-scc.yaml
contributes to: https://github.ibm.com/event-integration/sp-planning/issues/3409
Signed-off-by: Vignesh Kumar Elumalai <vigneshkumar.elumalai@ibm.com>
> Adding ea-scc.yaml

- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start-with-API-Connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start.yaml
add in required admin endpoint.
> Update the eem samples for 11.1.0

- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/README.md
- event-endpoint-management/cr-examples/eventgateway/kubernetes/README.md
- event-endpoint-management/cr-examples/eventgateway/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventgateway/kubernetes/quick-start.yaml
doing this to keep it consistent across the repo externally and internally
> update the cluster host name variable

- support/README.md
- support/restricted-must-gather.sh
This initial version only has options for EEM/EP/Flink/ES, it does not include all the module options that are available for the full must gather, notably missing:
- kafka
- schema
- failures
- failure
- system
- overview
> Introduce a minimal must gather for EEM/EP/Flink/ES

- event-processing/cr-examples/eventprocessing/kubernetes/README.md
- event-processing/cr-examples/eventprocessing/kubernetes/production.yaml
- event-processing/cr-examples/eventprocessing/openshift/README.md
- event-processing/cr-examples/eventprocessing/openshift/production.yaml
- flink/cr-examples/flinkdeployment/kubernetes/README.md
- flink/cr-examples/flinkdeployment/kubernetes/minimal-production.yaml
- flink/cr-examples/flinkdeployment/kubernetes/production-application-cluster.yaml
- flink/cr-examples/flinkdeployment/kubernetes/production.yaml
- flink/cr-examples/flinkdeployment/openshift/README.md
- flink/cr-examples/flinkdeployment/openshift/minimal-production.yaml
- flink/cr-examples/flinkdeployment/openshift/production-application-cluster.yaml
- flink/cr-examples/flinkdeployment/openshift/production.yaml
- flink/tls-setup/README.md
- flink/tls-setup/create-cluster-issuer.yaml
- flink/tls-setup/create-flink-deployment-jks-certificate.yaml
- flink/tls-setup/create-flink-operator-jks-certificate.yaml
Modify samples for flink and ep to use tls for flink deployments
> Flink/EP 1.1.4

- event-processing/flink-examples/udf/.gitignore
- event-processing/flink-examples/udf/Dockerfile
- event-processing/flink-examples/udf/README.md
- event-processing/flink-examples/udf/build-flink-image.sh
- event-processing/flink-examples/udf/build-maven-project.sh
- event-processing/flink-examples/udf/docker-compose/.env
- event-processing/flink-examples/udf/docker-compose/docker-compose.yaml
- event-processing/flink-examples/udf/flink-cluster.sh
- event-processing/flink-examples/udf/pom.xml
- event-processing/flink-examples/udf/sql/scalar-function-udf.sql
- event-processing/flink-examples/udf/sql/sentences.ndjson
- event-processing/flink-examples/udf/sql/table-function-udf.sql
- event-processing/flink-examples/udf/src/main/java/com/ibm/flink/udf/scalar/CustomScalarFunction.java
- event-processing/flink-examples/udf/src/main/java/com/ibm/flink/udf/scalar/StandaloneDryRun.java
- event-processing/flink-examples/udf/src/main/java/com/ibm/flink/udf/table/CustomTableFunction.java
- event-processing/flink-examples/udf/src/main/java/com/ibm/flink/udf/table/StandaloneDryRun.java
- event-processing/flink-examples/udf/src/test/java/com/ibm/flink/udf/scalar/CustomScalarFunctionTest.java
- event-processing/flink-examples/udf/src/test/java/com/ibm/flink/udf/table/CustomTableFunctionTest.java
- event-processing/flink-examples/udf/src/test/java/com/ibm/flink/udf/util/Util.java
Add a sample project for implementing Flink User-defined functions that can be used in the SQL exported from the Event Processing UI.
> feat: add a sample project for Flink User-defined functions

- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start-with-API-Connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/production.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/quick-start-with-api-connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/quick-start.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/usage-based-pricing.yaml
- event-endpoint-management/cr-examples/eventgateway/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventgateway/kubernetes/quick-start.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/production.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/quick-start.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/usage-based-pricing.yaml
This PR adds the license to the samples for EEM.
> Update samples to include latest license

- support/template-yaml/namespace.yaml
Adds a label to mustgather namespace.
> Add label to mustgather namespace

- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start-with-API-Connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/production.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/quick-start-with-api-connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/quick-start.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/usage-based-pricing.yaml
- event-endpoint-management/cr-examples/eventgateway/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventgateway/kubernetes/quick-start.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/production.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/quick-start.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/usage-based-pricing.yaml
Update to latest license on samples
> Update EEM samples for 11.4.0

- flink/cr-examples/flinkdeployment/kubernetes/README.md
- flink/cr-examples/flinkdeployment/kubernetes/production-application-cluster.yaml
- flink/cr-examples/flinkdeployment/openshift/README.md
- flink/cr-examples/flinkdeployment/openshift/production-application-cluster.yaml
* Update Application mode Flink sample for v1.2.3.
* Adjust the wording in the READMEs accordingly - and consistently with the rewording in the product doc.
> feat: update app mode Flink samples for Flink 1.2.3.

- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start-with-API-Connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/quick-start-with-api-connect-integration.yaml
Contributes to: https://jsw.ibm.com/browse/EVI-0
Signed off by: Adam L.Smith <adam.l.smith@ibm.com>
> feat: add tls trusted certs to eem apic integration samples

- event-streams/cr-examples/eventstreams/kubernetes/development.yaml
- event-streams/cr-examples/eventstreams/kubernetes/light-insecure.yaml
- event-streams/cr-examples/eventstreams/kubernetes/minimal-prod.yaml
- event-streams/cr-examples/eventstreams/kubernetes/prod-3-brokers.yaml
- event-streams/cr-examples/eventstreams/kubernetes/prod-6-brokers.yaml
- event-streams/cr-examples/eventstreams/kubernetes/prod-9-brokers.yaml
- event-streams/cr-examples/eventstreams/openshift/development-scram.yaml
- event-streams/cr-examples/eventstreams/openshift/development.yaml
- event-streams/cr-examples/eventstreams/openshift/light-insecure.yaml
- event-streams/cr-examples/eventstreams/openshift/minimal-prod-scram.yaml
- event-streams/cr-examples/eventstreams/openshift/minimal-prod.yaml
- event-streams/cr-examples/eventstreams/openshift/prod-3-brokers.yaml
- event-streams/cr-examples/eventstreams/openshift/prod-6-brokers.yaml
- event-streams/cr-examples/eventstreams/openshift/prod-9-brokers.yaml
Contributes to: https://jsw.ibm.com/browse/EVI-0
> feat: Samples update for 11.6.1

- flink/cr-examples/flinkdeployment/kubernetes/minimal-production.yaml
- flink/cr-examples/flinkdeployment/kubernetes/production-application-cluster.yaml
- flink/cr-examples/flinkdeployment/kubernetes/production.yaml
- flink/cr-examples/flinkdeployment/kubernetes/quick-start.yaml
- flink/cr-examples/flinkdeployment/openshift/minimal-production.yaml
- flink/cr-examples/flinkdeployment/openshift/production-application-cluster.yaml
- flink/cr-examples/flinkdeployment/openshift/production.yaml
- flink/cr-examples/flinkdeployment/openshift/quick-start.yaml
Update Flink Deployment samples for v1.3.2
> Update Flink Deployment sample

- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start-with-API-Connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/kubernetes/quick-start.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/production.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/quick-start-with-api-connect-integration.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/quick-start.yaml
- event-endpoint-management/cr-examples/eventendpointmanagement/openshift/usage-based-pricing.yaml
- event-endpoint-management/cr-examples/eventgateway/kubernetes/production.yaml
- event-endpoint-management/cr-examples/eventgateway/kubernetes/quick-start.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/production.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/quick-start.yaml
- event-endpoint-management/cr-examples/eventgateway/openshift/usage-based-pricing.yaml
Update EEM samples with new license
> Update samples with 11.6.1 license
